FROM ruby:2.7.3

ENV RAILS_ENV=production

RUN apt-get update -qq
RUN apt-get install -y nodejs npm postgresql-client imagemagick graphviz && npm install n -g && n lts
RUN apt-get install -y cron
RUN apt-get install -y vim
RUN npm install -g yarn
RUN service cron start
RUN mkdir /app
WORKDIR /app

# このDockerfileでgemのインストールやyarnによるパッケージのインストールをしていないのは、
# ログインなどの処理を挟む必要があるため。
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
COPY . /app
RUN bundle config --local set path 'vendor/bundle' \
  && bundle install

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

COPY start.sh /start.sh
RUN chmod 744 /start.sh
CMD ["sh", "/start.sh"]

